### ISSUE TITLE
v0.4 release - web UI doesn't show directory of mounted volumes.

### ISSUE THREAD

**Issue by jkimbroughTego** [NetAppLabs/genai-toolkit-deployments#37]
---
name: Bug report
about: Report a bug or technical issue
title: "v0.4 release - web UI doesn't show directories of mounted volumes."
labels: bug
assignees: ''

---

**Describe the issue**
Created an verifiable GCNV for the GenAI toolkit to mount, loaded it with data from wikipedia dumps.
GenAI shows the volume in dropdowns during initial RAG configuration. However attempts select a subfolder by clicking on 
eyeglass results in 500 error trying to open http://<ipaddr>/apiv1/prompt/ .... looking for an index-CSBXXXX.js file

asked prompt to give me a listing of files in /volumes/gcnv/<volname> and it gave a listing of 12 files
file1-12.txt - doesn't appear that the actual NFS volume is mounted. Looking over the bootstrap script not seeing the mechanism by which the docker image would mount those filesystems

**To Reproduce**
deploy Netapp GenAI toolkit v04 into GCP environment

**Expected behavior**
When click on google cloud netapp volumes there to be a list of folders from mounted NFS volume to select focus AI queries on.

**Screenshots**
![image](https://github.com/user-attachments/assets/5c8301c9-a3f3-4ced-964d-6aca583132c2)
![image](https://github.com/user-attachments/assets/dc62b0a2-4c09-4c95-9586-1e1104545a91)

**Desktop (please complete the following information):**
 - OS: Fedora 39
 - Browser Chrome
 - Browser version 130.0.6723.116

**Additional context**

**Comment by jkimbroughTego** [comment]
I did see the volume statements in the docker_compose.yml - so I guess your accessing the NFS mounts via host mounts. there goes that thought...

**Comment by hagnadarreglan** [comment]
this should be fixed in the 0.6.0 version available now at 
https://github.com/NetAppLabs/genai-toolkit-deployments
closing this issue for now
